#!/bin/sh

DOTNET_CLI_TELEMETRY_OPTOUT=1
HOMEBREW_NO_ANALYTICS=1
HOMEBREW_NO_AUTO_UPDATE=1
PYENV_ROOT=$HOME/.pyenv
PATH=$HOME/bin:$PYENV_ROOT/bin:$PATH

export DOTNET_CLI_TELEMETRY_OPTOUT HOMEBREW_NO_ANALYTICS HOMEBREW_NO_AUTO_UPDATES PYENV_ROOT PATH

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
