#!/bin/sh

DOTNET_CLI_TELEMETRY_OPTOUT=1
HOMEBREW_NO_ANALYTICS=1
HOMEBREW_NO_AUTO_UPDATE=1
PATH=$HOME/bin:$PATH

export DOTNET_CLI_TELEMETRY_OPTOUT HOMEBREW_NO_ANALYTICS HOMEBREW_NO_AUTO_UPDATES PATH
